version: '3.8'

services:
  tobi:
    build: .
    container_name: tobi-bot
    ports:
      - "5000:5000"
    volumes:
      - ./generated:/app/generated
      - ./logs:/app/logs
      - ./backups:/app/backups
    environment:
      - FLASK_APP=chatbot.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 